# Generated by Django 4.1.4 on 2022-12-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("articul", models.CharField(max_length=150, verbose_name="Артикул")),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "В наличии"),
                            ("2", "Под заказ"),
                            ("3", "Ожидается поступление"),
                            ("4", "Нет в наличии"),
                            ("5", "Не производится"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
